name: Cloudways API Git Pull

on: push

jobs:
  tag:
    name: New Tag

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cloudways API Git Pull
        uses: roelmagdaleno/cloudways-api-git-pull-action@stable
        with:
          email: ${{ secrets.CLOUDWAYS_EMAIL }}
          api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
          server-id: ${{ secrets.CLOUDWAYS_SERVER_ID }}
          app-id: ${{ secrets.CLOUDWAYS_APP_ID }}
          branch-name: ${{ secrets.CLOUDWAYS_BRANCH_NAME }}
          deploy-path: ''
